#!/usr/bin/expect -f
spawn /bin/sh -c "python3 -m manage createsuperuser"
expect -re "Username (leave blank to use 'root'): "
send "djadmin\r"
expect -re "Email address:"
send "djadmin@admin.local\r"
expect -re "Password:"
send "DStqZL2ay0cppqEkHq\r"
expect -re "Password (again):"
send "DStqZL2ay0cppqEkHq"
expect -re "Superuser created successfully."
