# Generated by Django 4.1.2 on 2022-10-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kauthappusersapi", "0004_clientaccesstoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientaccesstoken",
            name="user",
        ),
    ]
